# --- NFCNotes configuration file --- #
# If you have any issue, check your configuration is updated before submitting the issue! #

# --------------------------------------------------------------------------------------------------------- #
# [!] This is IMPORTANT if you already have notes created and you want to change any value of this category.
# [!] Remember that if you change any of these options and a plugin is using your old notes,
# [!] these must be changed or newer notes won't work on that plugin.
# --------------------------------------------------------------------------------------------------------- #
# Available placeholders for name and lore: {money}, {issuer}
# If you use any plugin that requires notes to be identical like Shopkeepers, you can remove the {issuer}
# placeholder.
# --------------------------------------------------------------------------------------------------------- #
# If you want to change the material, check https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
# before modifying the value, otherwise it may break.
# --------------------------------------------------------------------------------------------------------- #
notes:
  name: "&aNFCNote"
  lore:
    - "&7Value: &e{money}$"
    - "&7Issuer: &e{issuer}"
  material: PAPER
  use-decimals: false
  # This option will use commas instead of dots for decimal values #
  use-european-format: false
  # -------------------------------------------------------------------------------------------------------- #
  # Do not modify these values unless you know what you're doing. Changing them can break your existing notes.
  # More than two decimals is not allowed due to imprecise math operations. Inputs with more than two
  # decimals will be rounded.
  #decimal-format: "#,###"
  decimal-format: "#,###.##"
  # Attribute UUID
  identifier: 9a12cb32-1a7e-4e41-be79-9938528b4375
  # -------------------------------------------------------------------------------------------------------- #

# ------------------------------------------------------------------------------------------ #
# "base" value is required to be enabled in order to other modules from the same type to work.
# For example, if modules.deposit.action.base is disabled, "massdeposit" will also be, but
# the values from modules.deposit.command won't.
# ------------------------------------------------------------------------------------------ #
# Meaning of some values
# WITHDRAW
# withdraw-all - "/withdraw all"
# multiple-withdraw - "/withdraw [value] [amount]"
# DEPOSIT
# action.base - Right click to redeem one of the notes you're holding.
# massdeposit - Shift + Right click to redeem all the notes from your inventory.
# deposit-one - "/deposit"
# deposit-all - "/deposit all" (inventory)
# deposit-stack - "/deposit stack"
# ------------------------------------------------------------------------------------------ #
modules:
  withdraw:
    base: true
    withdraw-all: true
    multiple-withdraw: true
  deposit:
    action:
      base: true
      massdeposit: true
    command:
      deposit-one: true
      deposit-multiple: true
      deposit-all: true
      deposit-stack: true
  warn-staff: true

# If you want to use a different economy plugin, you can set it here. Default: Vault
# Supported economy plugins: Vault, PlayerPoints, Essentials.
# Recommended plugin: Vault
economy-plugin: Vault

# This prevents player from withdrawing and redeeming notes in certain worlds.
# Players with the permission nfcnotes.staff.withdraw.bypass.disabled-world or nfcnotes.staff.deposit.bypass.disabled-world
# won't be affected by this.
disabled-worlds:
  - disabled_world

# Tables in this list won't be able to work with NFCNotes. This also should be compatible with future tables from new Minecraft versions.
disabled-tables:
  - ANVIL
  - BEACON
  - BLAST_FURNACE
  - BREWING
  - CARTOGRAPHY
  - ENCHANTING
  - FURNACE
  - GRINDSTONE
  - LOOM
  - SMITHING
  - SMOKER
  - STONECUTTER
  - WORKBENCH

# If 'warn-staff' is enabled, staff will get a message when a player withdraws or deposits more money than the specified here.
warn-staff-if-value-is-higher-than: 100000

# This enables /nfcnotes with no arguments.
show-plugin-info: true

# Update checker
update-checker:
  enable: true # If true, each time the server starts you will receive a message if there is a newer version.
  notify-on-join: true # If enabled and a new version is available, each time an user with the permission nfcnotes.staff.check-updates connects to the server will be notified of the new version.

# Do not touch this unless it is indicated otherwise.
config-version: 10

# --- This is the end of this file, trust me --- #